/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCuzkRouteImport } from './routes/admin/cuzk'
import { Route as AdminMonitoringRouteImport } from './routes/admin/monitoring'
import { Route as AdminSsoRouteImport } from './routes/admin/sso'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiMonitoringRouteImport } from './routes/api/monitoring'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSsoLinkCallbackRouteImport } from './routes/api/sso-link/callback'
import { Route as DashboardWatchesIdRouteImport } from './routes/dashboard/watches/$id'
import { Route as DashboardWatchesNewRouteImport } from './routes/dashboard/watches/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCuzkRoute = AdminCuzkRouteImport.update({
  id: '/admin/cuzk',
  path: '/admin/cuzk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSsoRoute = AdminSsoRouteImport.update({
  id: '/admin/sso',
  path: '/admin/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitoringRoute = ApiMonitoringRouteImport.update({
  id: '/api/monitoring',
  path: '/api/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/dashboard/account',
  path: '/dashboard/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoLinkCallbackRoute = ApiSsoLinkCallbackRouteImport.update({
  id: '/api/sso-link/callback',
  path: '/api/sso-link/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWatchesIdRoute = DashboardWatchesIdRouteImport.update({
  id: '/dashboard/watches/$id',
  path: '/dashboard/watches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWatchesNewRoute = DashboardWatchesNewRouteImport.update({
  id: '/dashboard/watches/new',
  path: '/dashboard/watches/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/readyz': typeof ReadyzRoute
  '/signup': typeof SignupRoute
  '/admin/cuzk': typeof AdminCuzkRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/sso': typeof AdminSsoRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/monitoring': typeof ApiMonitoringRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sso-link/callback': typeof ApiSsoLinkCallbackRoute
  '/dashboard/watches/$id': typeof DashboardWatchesIdRoute
  '/dashboard/watches/new': typeof DashboardWatchesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/readyz': typeof ReadyzRoute
  '/signup': typeof SignupRoute
  '/admin/cuzk': typeof AdminCuzkRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/sso': typeof AdminSsoRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/monitoring': typeof ApiMonitoringRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sso-link/callback': typeof ApiSsoLinkCallbackRoute
  '/dashboard/watches/$id': typeof DashboardWatchesIdRoute
  '/dashboard/watches/new': typeof DashboardWatchesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/readyz': typeof ReadyzRoute
  '/signup': typeof SignupRoute
  '/admin/cuzk': typeof AdminCuzkRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/sso': typeof AdminSsoRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/monitoring': typeof ApiMonitoringRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sso-link/callback': typeof ApiSsoLinkCallbackRoute
  '/dashboard/watches/$id': typeof DashboardWatchesIdRoute
  '/dashboard/watches/new': typeof DashboardWatchesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/login'
    | '/readyz'
    | '/signup'
    | '/admin/cuzk'
    | '/admin/monitoring'
    | '/admin/sso'
    | '/api/metrics'
    | '/api/monitoring'
    | '/dashboard/account'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/api/sso-link/callback'
    | '/dashboard/watches/$id'
    | '/dashboard/watches/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthz'
    | '/login'
    | '/readyz'
    | '/signup'
    | '/admin/cuzk'
    | '/admin/monitoring'
    | '/admin/sso'
    | '/api/metrics'
    | '/api/monitoring'
    | '/dashboard/account'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/api/sso-link/callback'
    | '/dashboard/watches/$id'
    | '/dashboard/watches/new'
  id:
    | '__root__'
    | '/'
    | '/healthz'
    | '/login'
    | '/readyz'
    | '/signup'
    | '/admin/cuzk'
    | '/admin/monitoring'
    | '/admin/sso'
    | '/api/metrics'
    | '/api/monitoring'
    | '/dashboard/account'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/api/sso-link/callback'
    | '/dashboard/watches/$id'
    | '/dashboard/watches/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  ReadyzRoute: typeof ReadyzRoute
  SignupRoute: typeof SignupRoute
  AdminCuzkRoute: typeof AdminCuzkRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminSsoRoute: typeof AdminSsoRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  ApiMonitoringRoute: typeof ApiMonitoringRoute
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSsoLinkCallbackRoute: typeof ApiSsoLinkCallbackRoute
  DashboardWatchesIdRoute: typeof DashboardWatchesIdRoute
  DashboardWatchesNewRoute: typeof DashboardWatchesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cuzk': {
      id: '/admin/cuzk'
      path: '/admin/cuzk'
      fullPath: '/admin/cuzk'
      preLoaderRoute: typeof AdminCuzkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sso': {
      id: '/admin/sso'
      path: '/admin/sso'
      fullPath: '/admin/sso'
      preLoaderRoute: typeof AdminSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitoring': {
      id: '/api/monitoring'
      path: '/api/monitoring'
      fullPath: '/api/monitoring'
      preLoaderRoute: typeof ApiMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/dashboard/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso-link/callback': {
      id: '/api/sso-link/callback'
      path: '/api/sso-link/callback'
      fullPath: '/api/sso-link/callback'
      preLoaderRoute: typeof ApiSsoLinkCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/watches/$id': {
      id: '/dashboard/watches/$id'
      path: '/dashboard/watches/$id'
      fullPath: '/dashboard/watches/$id'
      preLoaderRoute: typeof DashboardWatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/watches/new': {
      id: '/dashboard/watches/new'
      path: '/dashboard/watches/new'
      fullPath: '/dashboard/watches/new'
      preLoaderRoute: typeof DashboardWatchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  ReadyzRoute: ReadyzRoute,
  SignupRoute: SignupRoute,
  AdminCuzkRoute: AdminCuzkRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminSsoRoute: AdminSsoRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  ApiMonitoringRoute: ApiMonitoringRoute,
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSsoLinkCallbackRoute: ApiSsoLinkCallbackRoute,
  DashboardWatchesIdRoute: DashboardWatchesIdRoute,
  DashboardWatchesNewRoute: DashboardWatchesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
