/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardWatchesIdRouteImport } from './routes/dashboard/watches/$id'
import { Route as DashboardWatchesNewRouteImport } from './routes/dashboard/watches/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/dashboard/account',
  path: '/dashboard/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWatchesIdRoute = DashboardWatchesIdRouteImport.update({
  id: '/dashboard/watches/$id',
  path: '/dashboard/watches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWatchesNewRoute = DashboardWatchesNewRouteImport.update({
  id: '/dashboard/watches/new',
  path: '/dashboard/watches/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/watches/$id': typeof DashboardWatchesIdRoute
  '/dashboard/watches/new': typeof DashboardWatchesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/watches/$id': typeof DashboardWatchesIdRoute
  '/dashboard/watches/new': typeof DashboardWatchesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/watches/$id': typeof DashboardWatchesIdRoute
  '/dashboard/watches/new': typeof DashboardWatchesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/login'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/dashboard/watches/$id'
    | '/dashboard/watches/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthz'
    | '/login'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/dashboard/watches/$id'
    | '/dashboard/watches/new'
  id:
    | '__root__'
    | '/'
    | '/healthz'
    | '/login'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/dashboard/watches/$id'
    | '/dashboard/watches/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DashboardWatchesIdRoute: typeof DashboardWatchesIdRoute
  DashboardWatchesNewRoute: typeof DashboardWatchesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/dashboard/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/watches/$id': {
      id: '/dashboard/watches/$id'
      path: '/dashboard/watches/$id'
      fullPath: '/dashboard/watches/$id'
      preLoaderRoute: typeof DashboardWatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/watches/new': {
      id: '/dashboard/watches/new'
      path: '/dashboard/watches/new'
      fullPath: '/dashboard/watches/new'
      preLoaderRoute: typeof DashboardWatchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DashboardWatchesIdRoute: DashboardWatchesIdRoute,
  DashboardWatchesNewRoute: DashboardWatchesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
